---
- name: Bootup AWS instance Play
  hosts: localhost
  connection: local
 
  roles:
    - aws

- name: Demo Configuration for AWS instance
  hosts: tag_demo_demosrv
  become: true
  become_user: root
  roles:
    - common
    - wordpress

