---
- name: Bootup AWS instance Play
  hosts: localhost
  connection: local
  gather_facts: no

  roles:
    - { role: aws_destroy, tags: remove } 
    - { role: aws, tags: setup }

#- name: Demo Configuration for AWS instance
#  hosts: tag_demo_demosrv
#  become: true
#  become_user: root
#  roles:
#    - wordpress
#    - common
#    - ansible
#  tags: demo

