---
- name: Bootup AWS instance Play
  hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - aws

- name: Configuration for AWS instance Play
  hosts: tag_demo_demosrv
  become: true
  become_user: root
  roles:
    - common
    - ansible
  tags: demo

