- name: Create AMI from instance
  ec2_ami:
    name: newtest
    state: present
    region: "{{ region }}"
    instance_id: "{{ myinstance }}"
    no_reboot: yes
    wait: no
  register: instance
  tags: demo


- name: Deregister AMI (delete associated snapshots too)
  ec2_ami:
    state: absent
    image_id: "{{ instance.image_id }}"
    region: "{{ region }}"
    delete_snapshot: True
  tags: ami-del

