---
- name: Create AMI from instance
  ec2_ami:
    name: share-ami-image
    state: present
    region: "{{ region }}"
    instance_id: "{{ instance_id }}"
    no_reboot: yes
    wait: no
    #launch_permissions:
    #  group_names: ['all']
  register: image_ret
#- debug: msg="{{ image_ret }}" 
