---
- ec2_vpc_igw:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    state: present
    vpc_id: "{{ vpc_id }}"
    region: "{{ region }}"
  register: myigw
  tags: c
