---
- block:
    - name: Create AWS Instance
      ec2:
        key_name: "{{ my_key }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        region: "{{ region }}"
        group: "{{ sec_group }}"
        vpc_subnet_id: "{{ vpc_subnet_id }}"
        exact_count: "{{ icnt }}"
        assign_public_ip: yes
        wait: yes
        count_tag:
          demo: demosrv
        instance_tags: 
          demo: demosrv
      register: myec2

    - meta: end_play

    - name: Add new instance to host group
      add_host: hostname="{{ item.public_ip }}" groupname=tag_demo_demosrv
      with_items: "{{ myec2.instances }}"

    - name: Wait for SSH to come up
      wait_for: host="{{ item.public_dns_name }}" port=22 delay=30 timeout=320 state=started
      with_items: "{{ myec2.instances }}"

