---
- name: Set up public subnet route table
  ec2_vpc_route_table:
    state: present
    region: "{{ region }}"
    vpc_id: "{{ vpc_id }}"
    tags:
       Name: demo
    subnets:
      - "{{ vpc_subnet_id }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ gateway_id }}"
