---
- name: Set up public subnet route table
  ec2_vpc_route_table:
    state: present
    vpc_id: "{{ vpc_id }}"
    region: "{{ region }}"
    tags:
       Name: Public
    subnets:
      - "{{ vpc_subnet_id }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ gateway_id }}"
  tags: demo

- ec2_vpc_route_table_facts:
    region: "{{ region }}"
    filters:
      vpc-id: "{{ vpc_id }}"
  register: myroutet
  tags: demo
