- name: Create AWS VPC 
  ec2_vpc_net:
    state: present
    region: "{{ region }}"
    name: "{{ vpcname }}"
    cidr_block: "{{ vpc_cidr_block }}"
    tags:
      Name: demo
    tenancy: default
  register: myvpc
