- name: Create VPC 
  ec2_vpc_net:
    state: present
    name: "{{ vpcname }}"
    cidr_block: "{{ vpc_cidr_block }}"
    region: "{{ region }}"
    tags:
      Name: demo
    tenancy: default
  register: myvpc

- debug: msg="{{ myvpc.vpc.id }}"
