- name: Create VPC 
  ec2_vpc_net:
    state: present
    name: MyVPC
    cidr_block: 10.0.0.0/16
    region: "{{ region }}"
    tags:
      Name: demo
    tenancy: default
  register: myvpc
  tags: demo

- name: Remove VPC 
  ec2_vpc_net:
    state: absent
    name: MyVPC
    region: "{{ region }}"
    cidr_block: 10.0.0.0/16
  tags: vpc-del

- debug: msg="{{ myvpc.vpc.id }}"
  tags: demo
