---
- name: Create AWS VPC subnet
  ec2_vpc_subnet:
    state: present
    region: "{{ region }}"
    vpc_id: "{{ vpc_id }}"
    az: "{{ az1 }}"
    cidr: "{{ subnet_cidr_block }}"
    tags:
      Name: demo
  register: myvpcsubnet
