- name: Create subnet for Instance
  ec2_vpc_subnet:
    state: present
    vpc_id: "{{ vpc_id }}"
    region: "{{ region }}"
    az: "{{ az1 }}"
    cidr: "{{ subnet_cidr_block }}"
    tags:
      Name: demo
  register: myvpcsubnet

- debug: msg="{{ myvpcsubnet.subnet.id }}"
