---
- block:
  - debug: msg="{{ hostvars[demo_host].ec2_block_devices.sda1 }}"
  - debug: msg="{{ hostvars[demo_host].ec2_vpc_id }}"
  - debug: msg="{{ hostvars[demo_host].ec2_subnet_id }}"
  - debug: msg="{{ hostvars[demo_host].ec2_security_group_names }}"
  - debug: msg="{{ hostvars[demo_host].ec2_id }}"
  #- meta: end_play
  tags: test

- block:
  - name: Terminate Instance 
    ec2:
      state: absent
      region: "{{ region }}"
      instance_ids: 
        - "{{ hostvars[demo_host].ec2_id }}"
      wait: yes

  - name: Remove a key
    ec2_key:
      state: absent
      region: "{{ region }}"
      name: "{{ my_key }}"

  - name: Remove a volume
    ec2_vol:
      state: absent
      region: "{{ region }}"
      id: "{{ hostvars[demo_host].ec2_block_devices.sda1 }}"
  tags: rm_instance

- block:
  - name: Remove a subnet
    ec2_vpc_subnet:
      state: absent
      region: "{{ region }}"
      vpc_id: "{{ hostvars[demo_host].ec2_vpc_id }}"
      cidr: "{{ subnet_cidr_block }}"

  - name: Remove a internet gateway
    ec2_vpc_igw:
      state: absent
      region: "{{ region }}"
      vpc_id: "{{ hostvars[demo_host].ec2_vpc_id }}"

  - name: Remove subnets and route tables from VPC
    ec2_vpc:
      state: present
      vpc_id: "{{ hostvars[demo_host].ec2_vpc_id }}"
      region: "{{ region }}"
      resource_tags: "{}"
      subnets: []
      internet_gateway: False
      route_tables: []
  
  - name: Remove a security group
    ec2_group:
      state: absent
      region: "{{ region }}"
      name: "{{ hostvars[demo_host].ec2_security_group_names }}"
      description: My Rules 
      vpc_id: "{{ hostvars[demo_host].ec2_vpc_id }}"

  - name: Remove VPC
    ec2_vpc:
      state: absent
      region: "{{ region }}"
      vpc_id: "{{ hostvars[demo_host].ec2_vpc_id }}"
      resource_tags: "{}"
    tags: del_vpc1
  tags: rm_vpc

#- name: Deregister AMI (delete associated snapshots too)
#  ec2_ami:
#    state: absent
#    image_id: "{{ del_image_id }}"
#    region: "{{ region }}"
#    delete_snapshot: True
