---
- name: Change hostname
  hostname: name="{{ hname }}"
  
- block:
    - name: Install EPEL-Package
      yum: name=epel-release state=present

    - name: Install Packages
      yum: name={{ item }} state=latest
      with_items:
        - git

    - name: Stop and Disabled services
      service: name={{ item }} state=stopped enabled=no
      with_items:
        - postfix
        - wpa_supplicant
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"
